# Generated by Django 4.2.6 on 2023-10-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_net_manager', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.png', null=True, upload_to=''),
        ),
    ]
